// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM4rAM64lmWhiBpnnXV65JA-p-6BaJ32k',
    appId: '1:444196067478:web:f4468290db170bae99cab7',
    messagingSenderId: '444196067478',
    projectId: 'to-do-list-49769',
    authDomain: 'to-do-list-49769.firebaseapp.com',
    storageBucket: 'to-do-list-49769.appspot.com',
    measurementId: 'G-NCBG651T4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-doh-D4Z_J4AhCpn00Oi6ylbQpyxMSAA',
    appId: '1:444196067478:android:05b38eda7c58a15a99cab7',
    messagingSenderId: '444196067478',
    projectId: 'to-do-list-49769',
    storageBucket: 'to-do-list-49769.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPz6XfnmT75OvEoEfPeX7Qj1O3PPEYUs',
    appId: '1:444196067478:ios:09d4b3c3836cff3b99cab7',
    messagingSenderId: '444196067478',
    projectId: 'to-do-list-49769',
    storageBucket: 'to-do-list-49769.appspot.com',
    iosClientId: '444196067478-dt7uup485scbs9j2sg4mfr1qgoijg1ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM4rAM64lmWhiBpnnXV65JA-p-6BaJ32k',
    appId: '1:444196067478:web:1e5c56e7360b6c2299cab7',
    messagingSenderId: '444196067478',
    projectId: 'to-do-list-49769',
    authDomain: 'to-do-list-49769.firebaseapp.com',
    storageBucket: 'to-do-list-49769.appspot.com',
    measurementId: 'G-K32XECVDW6',
  );
}
